name = "riddle-me-this-api"
main = "src/index.ts"
compatibility_date = "2025-06-17"

[dev]
port = 8787

# Default variables for local development
[vars]
ENVIRONMENT = "development"

[ai]
binding = "AI"

# Development environment (remote dev worker for testing)
[env.development]
name = "riddle-me-this-api-dev"

[env.development.vars]
ENVIRONMENT = "development"
GOOGLE_SEARCH_ENGINE_ID = "a61de03c6209d4c31"
# GOOGLE_SEARCH_API_KEY should be set via: wrangler secret put GOOGLE_SEARCH_API_KEY

[env.development.ai]
binding = "AI"

# Production environment
[env.production]
name = "riddle-me-this-api"

[env.production.vars]
ENVIRONMENT = "production"
GOOGLE_SEARCH_ENGINE_ID = "a61de03c6209d4c31"
# GOOGLE_SEARCH_API_KEY should be set via: wrangler secret put GOOGLE_SEARCH_API_KEY --env production
APP_VERSION = "0.1.0"  # Updated by deployment process

[env.production.ai]
binding = "AI"

[observability.logs]
enabled = true

# Future configurations can be added here:
# [kv_namespaces]
# [r2_buckets]
# [d1_databases]
