name = "riddle-me-this-api"
main = "src/index.ts"
compatibility_date = "2025-06-30"

[ai]
binding = "AI"

# Development environment (remote dev worker for testing)
[env.development]
name = "riddle-me-this-api-dev"
vars = { ENVIRONMENT = "development" }

[env.development.ai]
binding = "AI"

# Production environment
[env.production]
name = "riddle-me-this-api"
vars = { ENVIRONMENT = "production" }

[env.production.ai]
binding = "AI"

# Future configurations can be added here:
# [kv_namespaces]
# [r2_buckets]
# [d1_databases]
# [observability]
